# Automatically generated by make - do not edit


LOGIN := $(SSH) $(HOST)
SSH := ssh -A -i ~/.ssh/id_martinvirtel_server_2017
INSTANCE := i-09e2a087542cfdb65
HOST := ubuntu@52.59.92.166
HOST_IP := 52.59.92.166
